config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root  'categories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :categories do
    collection do
      get :manage_categories #for breadcrumbs
      get '/favorite' => :fav_category
    end
    member do
      get '/update' => :update_fav_category
    end
  end

  resources :topics do
    collection do
      get :manage_topics
      get '/favorite/list' => :link_topic
    end
    member do
      get '/category/topics' => :supply_topic
      get '/favorite' => :fav_topic
      get '/update' => :update_fav_topic
    end
  end

  resources :links do
    collection do
      get :manage_links
      get 'favorite/list' => :fav_link_all
    end
    member do
      get '/category/topic/links' => :get_link
      get '/favorite' => :fav_link
      get '/update' => :update_fav_link
    end
  end
  resources :user_informations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :links, :dependent => :destroy
  before_save :smart_capitalize

  validates :name, :presence => true
  validates_uniqueness_of :name, :scope => [:user_id]
  validates :description, :length => {:maximum => 918}

  def self.search(catagory,search, id)
    if search
      where("category_id = ? and user_id = ? and lower(name) like ? ", catagory, id, "%#{search.downcase}%").order("name ASC")
    else
      where("category_id = ? and user_id = ? ", catagory, id).order("name ASC")
    end
  end

  def self.fav_search(catagory, search, id)
    if search
      where("category_id = ? and user_id = ? and lower(name) like ? and favorite = ? ", catagory, id, "%#{search.downcase}%", true).order("name ASC")
    else
      where("category_id = ? and user_id = ? and favorite = ? ", catagory, id, true).order("name ASC")
    end
  end

  def self.fav_search_all(search, id)
    if search
      where("user_id = ? and lower(name) like ? and favorite = ? ", id, "%#{search.downcase}%", true).order("name ASC")
    else
      where("user_id = ? and favorite = ? ",id, true).order("name ASC")
    end
  end

  protected

  def smart_capitalize
    self.name = self.name.titleize
    self.description = self.description.capitalize
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  add_breadcrumb "Home", :authenticated_root_path
  add_breadcrumb "Topics", :topics_path
  def new
    @title = "Add"
    add_breadcrumb "New"
    @topic = Topic.new
    @category_list = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @category_list = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
    if @topic.save
      flash[:success] = "Topic created."
      redirect_to :new_topic
    else
      flash[:error] = "Unable to create topic."
      render :new
    end
  end

  def edit
    @title = "Edit"
    add_breadcrumb "Edit"
    @topic = Topic.find(params[:id])
    @category_list = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:success] = "Topic Updated."
      redirect_to "/topics/" + @topic.category.id.to_s
    else
      flash[:error] = "Unable to update topic."
      @category_list = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
      render :edit
    end
  end

  def destroy
    @topic = Topic.destroy(params[:id])
    if @topic.destroyed?
      flash[:success] = "#{@topic.name} destroyed."
    else
      flash[:error] = "Unable to destroy #{@topic.name}"
    end
    redirect_to "/topics/" + @topic.category.id.to_s
  end

  def index #topic
    @title = "List"
    @category = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
  end

  def supply_topic
    @topic = Topic.search(params[:id], params[:search], current_user.id)
    render json: @topic
  end

  def show #category -> topic
    @title = "Topics"
    add_breadcrumb "List"
    @perpage = 12

    @topics = Topic.search(params[:id], params[:search], current_user.id)
    @topic = @topics.paginate(:page => params[:page], :per_page => @perpage)
    @page = params[:page] || 1
  end

  def fav_topic #fav_category -> fav_topic
    @title = "Favourite | List"
    add_breadcrumb "Favourite"
    @perpage = 1
    @topics = Topic.fav_search(params[:id], params[:search], current_user.id)
    @topic = @topics.paginate(:page => params[:page], :per_page => @perpage)
    @page = params[:page] || 1
  end

  def link_topic #total fav topics
    @title = "Favorite | List"
    add_breadcrumb "Favorite"
    @topics = Topic.fav_search_all(params[:search],current_user.id)
    @perpage = 12
    @topic = @topics.paginate(:page => params[:page], :per_page => @perpage)
  end

  def update_fav_topic
    @topic = Topic.find(params[:id])
    if @topic.favorite.present?
      @topic.favorite = false
      printf "topic: #{@topic.favorite}"
    else
      @topic.favorite = true
    end
    @topic.save
    render json: @topic.favorite
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :category_id, :favorite)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2  ">

    <% if @topic.errors.any? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <ul>
            <% @topic.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="well">
      <%= form_for @topic do |f| %>
          <div class="form-horizontal">
            <div class="form-group">
              <label class="control-label col-md-3">Category<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <%= f.collection_select :category_id, @category_list, :id, :name, {prompt: "Select Category"}, :class => "form-control select" %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Name <span class="text-danger">*</span></label>
              <div class="col-md-9">
                <%= f.text_field :name, :class=>"form-control", :placeholder => "Youtube" %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Description </label>
              <div class="col-md-9">
                <%= f.text_area :description,:rows => 4, :style => "resize: none;", :class=>"form-control", :placeholder => "Links related to videos." %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Favorite </label>
              <div class="col-md-9">
                <div class="check-box">
                  <%= f.check_box :favorite %>
                </div>
              </div>
            </div>


            <div class="form-group">
              <div class="col-md-offset-3 col-md-4">
                <%= f.submit "Submit", :class => "btn btn-primary"%>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/fav_topic.html.erb
<div class="catagory">
  <div class="row">

    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag topic_path, method: 'get' do %>
            <div class="col-xs-12 col-sm-8 col-md-6 form-group">
              <%= text_field_tag :search, params[:search], :class => "form-control" %>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_topic_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>

    <div class="col-xs-12 col-md-12">
      <hr>
    </div>

    <div class="col-md-12 ">
      <% if !@topics.present? %>
          <div class="text-center text-primary">
            <h3>Favorite topic doesnot exist for his category.</h3>
          </div>
      <% else %>
          <% @topic.each do |f| %>
              <% if (f.description.present?)
                   @value = f.description
                 else
                   @value = "No Description."
                 end%>
              <div class="col-md-6 ">
                <div class="panel panel-primary">
                  <div class="panel-body">

                    <div class="fa-icon">
                      <div class="pull-right">
                        <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="<%= topic_path(f) %>">
                            <span>
                              <i class="fa fa-trash fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <a href="<%= edit_topic_path(f) %>">
                            <span>
                              <i class="fa fa-edit fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <% if f.favorite %>
                            <i class="fa fa-star topic-fav fa-hide" name="<%= f.id %>" style="color: #f4bd2b">&nbsp;</i>
                        <% else %>
                            <i class="fa fa-star topic-fav fa-hide" name="<%= f.id %>" >&nbsp;</i>
                        <% end %>
                        <a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= @value %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                      </div>
                    </div>

                    <div class="databody">
                      <a itemprop="url" href="<%= link_path(f) %>">
                        <h2 class="post-title"><%= f.name %></h2>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @topic, renderer: BootstrapPagination::Rails %>
<script type="text/javascript" charset="utf-8">
  $('body').on('click','.topic-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.topic-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/topics/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
  });

</script>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-6">
      <label class="col-md-4 control-label text-right">Category</label>
      <div class="col-md-8 ">
        <%= select_tag 'catagoryid', options_for_select( @category.collect{ |u| [u.name, u.id] } ), :prompt => "Select Unit", :class => "form-control select"%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="col-xs-12 col-sm-8 col-md-6 form-group">
        <input type="text" class="form-control input-search">
      </div>
      <div class="col-xs-12 col-sm-4 col-md-6">
        <p class="btn btn-success btn-search">Search</p>
      </div>
    </div>
  </div>

 <div class="col-md-12">
   <br>
   <hr>
   <br>
 </div>
  <div class="col-md-12 catagory">
    <div class="text-center text-primary catagory-remove">
      <h3>Topics not created for this category.</h3>
      <a href="<%= new_topic_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">

    $('body').on('change','#catagoryid', function () {
      var selectbox = $('.select');
      if(selectbox.val() != ''){
        $.ajax({
          url: '/topics/' + selectbox.val() + '/category/topics',
          error: function () {
            $('#info').html('<p>An error has occurred</p>');
          },
          success: function (data) {
            if (!$.trim(data)) {
              $('div.catagory-remove').remove();
              var add_div = '<div class="text-center text-primary catagory-remove"><h3>Topics not created.</h3> <a href="/topics/new" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a> </div>'
              $('div.catagory').append(add_div);
            } else {
              $('div.catagory-remove').remove();
              for (i = 0; i < data.length; i++) {
                var adddata = "";
                adddata = '<div class="col-md-6 catagory-remove"><div class="panel panel-primary" >';
                adddata += ' <div class="panel-body"><div class="fa-icon"><div class="pull-right"><a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="/topics/' + data[i].id ;
                adddata += '"><span><i class="fa fa-trash ">&nbsp;</i></span></a><a href="topics/' + data[i].id +'/edit';
                adddata += '"><span><i class="fa fa-edit ">&nbsp;</i></span></a>';
                if (data[i].favorite == true){
                  adddata += '<i class="fa fa-star topic-fav fa-hide" style="color: #f4bd2b" name="' + data[i].id + '">&nbsp;</i>';
                }else{
                  adddata += ' <i class="fa fa-star topic-fav fa-hide" name="' + data[i].id + '" >&nbsp;</i>';
                }
                adddata += '<a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="' + data[i].description + '"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>';
                adddata += '</div></div><div class="databody"> <a itemprop="url" href="/links/'+ data[i].id+ '">';
                adddata += '<h2 class="post-title">' + data[i].name + '</h2></a></div></div></div>';
                $('div.catagory').append(adddata);
              }
            }

          },
          type: 'GET'
        });
      }
    });

    $('body').on('click','.btn-search', function () {
      var selectbox = $('.select');
      if(selectbox.val() != ''){
        $.ajax({
          url: '/topics/' + selectbox.val() + '/category/topics?utf8=✓&search=' + $('.input-search').val(),
          error: function () {
            $('#info').html('<p>An error has occurred</p>');
          },
          success: function (data) {
            if (!$.trim(data)) {
              $('div.catagory-remove').remove();
              var add_div = '<div class="text-center text-primary catagory-remove"><h3>Topics not created.</h3> <a href="/topics/new" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a> </div>'
              $('div.catagory').append(add_div);
            } else {
              $('div.catagory-remove').remove();
              for (i = 0; i < data.length; i++) {
                var adddata = "";
                adddata = '<div class="col-md-6 catagory-remove"><div class="panel panel-primary" >';
                adddata += ' <div class="panel-body"><div class="fa-icon"><div class="pull-right"><a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="/topics/' + data[i].id ;
                adddata += '"><span><i class="fa fa-trash ">&nbsp;</i></span></a><a href="topics/' + data[i].id +'/edit';
                adddata += '"><span><i class="fa fa-edit ">&nbsp;</i></span></a>';
                if (data[i].favorite == true){
                  adddata += '<i class="fa fa-star topic-fav fa-hide" style="color: #f4bd2b" name="' + data[i].id + '">&nbsp;</i>';
                }else{
                  adddata += ' <i class="fa fa-star topic-fav fa-hide" name="' + data[i].id + '" >&nbsp;</i>';
                }
                adddata += '<a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="' + data[i].description + '"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>';
                adddata += '</div></div><div class="databody"> <a itemprop="url" href="/links/'+ data[i].id+ '" >';
                adddata += '<h2 class="post-title">' + data[i].name + '</h2></a></div></div></div>';
                $('div.catagory').append(adddata);
              }
            }
          },
          type: 'GET'
        });
      }
    });

    $('body').on('click','.btn-reset', function () {
      var selectbox = $('.select');
      if(selectbox.val() != ''){
        $.ajax({
          url: '/topics/' + selectbox.val() + '/category/topics',
          error: function () {
            $('#info').html('<p>An error has occurred</p>');
          },
          success: function (data) {
            if (!$.trim(data)) {
              $('div.link-remove').remove();
              var add_div = '<div class="text-center text-primary catagory-remove"><h3>Topics not created.</h3> <a href="/topics/new" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a> </div>'
              $('div.link').append(add_div);
            } else {
              $('div.link-remove').remove();
              for (i = 0; i < data.length; i++) {
                var adddata = "";
                adddata = '<div class="col-md-6 category-remove"><div class="panel panel-primary" >';
                adddata += ' <div class="panel-body"><div class="fa-icon"><div class="pull-right"><a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="/topics/' + data[i].id ;
                adddata += '"><span><i class="fa fa-trash ">&nbsp;</i></span></a><a href="topics/' + data[i].id +'/edit';
                adddata += '"><span><i class="fa fa-edit ">&nbsp;</i></span></a>';
                if (data[i].favorite == true){
                  adddata += '<i class="fa fa-star link-fav fa-hide" style="color: #f4bd2b" name="' + data[i].id + '">&nbsp;</i>';
                }else{
                  adddata += ' <i class="fa fa-star link-fav fa-hide" name="' + data[i].id + '" >&nbsp;</i>';
                }
                adddata += '<a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="' + data[i].description + '"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>';
                adddata += '</div></div><div class="databody"> <a itemprop="url" href="/links/'+ data[i].id+ '">';
                adddata += '<h2 class="post-title">' + data[i].name + '</h2></a></div></div></div>';
                $('div.link').append(adddata);
              }

            }
          },
          type: 'GET'
        });
      }
    });

    $('body').on('click','.topic-fav',function(e){
      var row = $(this).closest('div');
      var fav = $('.topic-fav',row);
      var name_value = fav.attr("name");
      $.ajax({
        url: '/topics/' + name_value + '/update',
        error: function () {
          $('#info').html('<p>An error has occurred</p>');
        },
        success: function (data) {
          if (data != ''){
            fav.css('color','#f4bd2b');
          }else{
            fav.css('color','#c2c2c2');
          }
        },
        type: 'GET'
      });
    });

    $(document).ready(function () {
      $('[data-toggle="toggle]').tooltip();
    });
</script>

app/views/topics/link_topic.html.erb
<div class="catagory">
  <div class="row">

    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag favorite_list_topics_path, method: 'get' do %>
            <div class="col-xs-12 col-sm-8 col-md-6 form-group">
              <%= text_field_tag :search, params[:search], :class => "form-control" %>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_topic_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>

    <div class="col-xs-12 col-md-12">
      <hr>
    </div>

    <div class="col-md-12 ">
      <% if !@topics.present? %>
          <div class="text-center text-primary">
            <h3>Topics not created for this user.</h3>
            <a href="<%= new_topic_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a>
          </div>
      <% else %>
          <% @topic.each do |f| %>
              <% if (f.description.present?)
                   @value = f.description
                 else
                   @value = "No Description."
                 end%>
              <div class="col-md-6 ">
                <div class="panel panel-primary">
                  <div class="panel-body">

                    <div class="fa-icon">
                      <div class="pull-right">
                        <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="<%= topic_path(f) %>">
                            <span>
                              <i class="fa fa-trash fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <a href="<%= edit_topic_path(f) %>" title="Edit" data-toggle="toggle">
                            <span>
                              <i class="fa fa-edit fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <% if f.favorite %>
                            <i class="fa fa-star category-fav fa-hide" title="Favourite" data-toggle="toggle" name="<%= f.id %>" style="color: #f4bd2b">&nbsp;</i>
                        <% else %>
                            <i class="fa fa-star category-fav fa-hide" title="Favourite" data-toggle="toggle" name="<%= f.id %>" >&nbsp;</i>
                        <% end %>
                        <a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= f.description %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                      </div>
                    </div>

                    <div class="databody">
                      <a itemprop="url" href="<%= link_path(f) %>">
                        <h2 class="post-title"><%= f.name %></h2>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @topic, renderer: BootstrapPagination::Rails %>
<script type="text/javascript" charset="utf-8">
  $('body').on('click','.category-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.category-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/topics/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        console.log(data);
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
  });

  $(document).ready(function () {
    $('[data-toggle="popover"]').popover();
    $('[data-toggle="toggle"]').tooltip();
  });
</script>

app/views/topics/show.html.erb
<div class="catagory">
  <div class="row">

    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag topic_path, method: 'get' do %>
            <div class="col-xs-12 col-sm-8 col-md-6 form-group">
              <%= text_field_tag :search, params[:search], :class => "form-control" %>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_topic_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>

    <div class="col-xs-12 col-md-12">
      <hr>
    </div>

    <div class="col-xs-12 col-md-12 ">
      <% if !@topics.present? %>
          <div class="text-center text-primary">
            <h3>Topics not created for this user.</h3>
            <a href="<%= new_topic_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a>
          </div>
      <% else %>
          <% @topic.each do |f| %>
              <% if (f.description.present?)
                   @value = f.description
                 else
                   @value = "No Description."
                 end%>
              <div class="col-md-6 ">
                <div class="panel panel-primary">
                  <div class="panel-body">

                    <div class="fa-icon">
                      <div class="pull-right">
                        <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete" data-toggle="toggle" data-method="delete" href="<%= topic_path(f) %>">
                            <span>
                              <i class="fa fa-trash fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <a href="<%= edit_topic_path(f) %>" title="Edit" data-toggle="toggle">
                            <span>
                              <i class="fa fa-edit fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <% if f.favorite %>
                            <i class="fa fa-star category-fav fa-hide" title="Favourite" data-toggle="toggle" name="<%= f.id %>" style="color: #f4bd2b">&nbsp;</i>
                        <% else %>
                            <i class="fa fa-star category-fav fa-hide" title="Favourite" data-toggle="toggle" name="<%= f.id %>" >&nbsp;</i>
                        <% end %>
                        <a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= f.description %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                      </div>
                    </div>

                    <div class="databody">
                      <a itemprop="url" href="<%= link_path(f) %>">
                        <h2 class="post-title"><%= f.name %></h2>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @topic, renderer: BootstrapPagination::Rails %>
<script type="text/javascript" charset="utf-8">
  $('body').on('click','.category-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.category-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/topics/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        console.log(data);
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
  });

  $(document).ready(function () {
    $('[data-toggle="popover"]').popover();
    $('[data-toggle="toggle"]').tooltip();
  });
</script>