config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root  'categories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :categories do
    collection do
      get :manage_categories #for breadcrumbs
      get '/favorite' => :fav_category
    end
    member do
      get '/update' => :update_fav_category
    end
  end

  resources :topics do
    collection do
      get :manage_topics
      get '/favorite/list' => :link_topic
    end
    member do
      get '/category/topics' => :supply_topic
      get '/favorite' => :fav_topic
      get '/update' => :update_fav_topic
    end
  end

  resources :links do
    collection do
      get :manage_links
      get 'favorite/list' => :fav_link_all
    end
    member do
      get '/category/topic/links' => :get_link
      get '/favorite' => :fav_link
      get '/update' => :update_fav_link
    end
  end
  resources :user_informations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_breadcrumb.html.erb
<% @data = controller.controller_name.to_s.titleize %>
<% if @check_title === "Category" %>

    <div class="page-header">
      <h3>
        <%= @data %>
        <small> | <%= @title %></small>
        </h4>
      </h3>
    </div>
    <ol class="breadcrumb">
      <a href="/">Home</a>
    </ol>
<% elsif @data === "User Informations" %>
    <div class="page-header">
      <% @user = UserInformation.find_by_user_id(current_user.id) %>
      <h3>
        User Profile
        <small> |
          <% if @user.nil? %>
              <%= current_user.email %>
          <% else %>
              <% if (@user.first_name.present? or @user.middle_name.present? or @user.last_name.present?) %>

                  <% if user_signed_in? %>
                      <% if @user.first_name.present? %>
                          <%= @user.first_name.slice(0, 1).capitalize + @user.first_name.slice(1..-1) %>
                      <% end %>
                      <% if @user.middle_name.present? %>
                          <%= @user.middle_name.slice(0, 1).capitalize + @user.middle_name.slice(1..-1) %>
                      <% end %>
                      <% if @user.last_name.present? %>
                          <%= @user.last_name.slice(0, 1).capitalize + @user.last_name.slice(1..-1) %>
                      <% end %>
                  <% end %>

              <% else %>
                  <%= current_user.email %>
              <% end %>
          <% end %>
        </small>
        </h4>
      </h3>
    </div>
    <ol class="breadcrumb">
      <a href="/">Home</a> / User Profile
    </ol>
<% elsif @data === "Registrations" %>
        <div class="page-header">
          <h3>
            Edit
            <small> |
              <% if @user.nil? %>
                  <%= current_user.email %>
              <% else %>
                  <% if (@user.first_name.present? or @user.middle_name.present? or @user.last_name.present?) %>

                      <% if user_signed_in? %>
                          <% if @user.first_name.present? %>
                              <%= @user.first_name.slice(0, 1).capitalize + @user.first_name.slice(1..-1) %>
                          <% end %>
                          <% if @user.middle_name.present? %>
                              <%= @user.middle_name.slice(0, 1).capitalize + @user.middle_name.slice(1..-1) %>
                          <% end %>
                          <% if @user.last_name.present? %>
                              <%= @user.last_name.slice(0, 1).capitalize + @user.last_name.slice(1..-1) %>
                          <% end %>
                      <% end %>

                  <% else %>
                      <%= current_user.email %>
                  <% end %>
              <% end %>
            </small>
            </h4>
          </h3>

        </div>
        <ol class="breadcrumb">
          <a href="<%= authenticated_root_path %>">Home</a><span> / Change Password</span>
        </ol>
<% else %>
      <div class="page-header">
        <h3>
          <%= @data %> <small> | <%=  @title %></small></h4>
        </h3>

      </div>
      <ol class="breadcrumb">
        <%= render_breadcrumbs :tag => :li, :separator => "" %>
      </ol>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-bottom">
  <br>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-xs-6 ">
        <p>Built with
          <i class="fa fa-heart fa-fw text-danger">&nbsp;</i>
          in Biratnagar
        </p>
      </div>
      <div class="col-md-6 col-xs-6">
        <p class="pull-right hidden-xs">&copy; 2017
          <span class="text-primary">Ginux </span><span class="text-danger">Innovation</span></p>
      </div>
    </div>
  </div>
  <br>
</div>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description"
        content="Linkstore is a simple to use web based application designed and developed using Rails framework of Ruby programming language(ROR).
                 Linkstore can be described as link bank that can store links for eternity.
                 You can divide link into three phase category, topic and finally link.">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>LinkStore</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>

app/views/shared/_navexample.html.erb
<div class="navmenu navmenu-default navmenu-fixed-left offcanvas">
  <a class="navmenu-brand" href="<%= unauthenticated_root_path %>"><h3><strong><span class="text-success">Link</span><span class="text-primary">Store</span></strong></h3></a>
  <ul class="nav navmenu-nav">

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" >
        <h4><i class="fa fa-plus">&nbsp;</i> Add <b class="caret"></b></h4>
      </a>
      <ul class="dropdown-menu navmenu-nav">
        <li><a href="<%= new_category_path %>">
                    <span>
                      <i class="fa fa-tree fa-fw">&nbsp;</i>
                    </span>
            Category
          </a>
        </li>

        <li>
          <a href="<%= new_topic_path %>">
                    <span>
                      <i class="fa fa-book fa-fw">&nbsp;</i>
                    </span>Title
          </a>
        </li>

        <li>
          <a href="<%= new_link_path %>">
                    <span>
                      <i class="fa fa-link fa-fw">&nbsp;</i>
                    </span>Link
          </a>
        </li>

      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" >
        <h4><i class="fa fa-binoculars">&nbsp;</i> View <span class="caret"></span></h4>
      </a>
      <ul class="dropdown-menu navmenu-nav">
        <li>
          <a href="<%= categories_path %>">
                    <span>
                      <i class="fa fa-tree fa-fw">&nbsp;</i>
                    </span>
            Category
          </a>
        </li>
        <li>
          <a href="<%= topics_path %>">
                    <span>
                      <i class="fa fa-book fa-fw">&nbsp;</i>
                    </span>Topics
          </a>
        </li>
        <li>
          <a href="<%= links_path %>">
                    <span>
                      <i class="fa fa-link fa-fw">&nbsp;</i>
                    </span>Links
          </a>
        </li>
      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" >
        <h4> <i class="fa fa-star">&nbsp;</i> Favourite <span class="caret"></span></h4>
      </a>
      <ul class="dropdown-menu navmenu-nav">
        <li>
          <a href="<%= favorite_categories_path %>">
                    <span>
                      <i class="fa fa-tree fa-fw">&nbsp;</i>
                    </span>
            Category
          </a>
        </li>
        <li>
          <a href="<%= favorite_list_topics_path %>">
                    <span>
                      <i class="fa fa-book fa-fw">&nbsp;</i>
                    </span>Topics
          </a>
        </li>
        <li>
          <a href="<%= favorite_list_links_path %>">
                    <span>
                      <i class="fa fa-link fa-fw">&nbsp;</i>
                    </span>Links
          </a>
        </li>
      </ul>
    </li>
  </ul>
</div>

<div class="navbar menubar navbar-default navbar-fixed-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navmenu" data-canvas="body">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

      <div class="pull-right">
        <ul class="nav navmenu-nav navbar-right ">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle">
              <% @user = UserInformation.find_by_user_id(current_user.id) %>
              <% if @user.nil? %>
                  <%= image_tag "picture.gif", class: "pp-avatar"%>
              <% else %>
                  <% if (@user.first_name.present? or @user.middle_name.present? or @user.last_name.present?) %>
                      <% if @user.photo.present? %>
                          <%= image_tag @user.photo.thumb.url, :class => "pp-avatar" %>
                      <% else %>
                          <%= image_tag "picture.gif", class: "pp-avatar" %>
                      <% end %>
                  <% else %>
                      <% if @user.photo.present? %>
                          <%= image_tag @user.photo.thumb.url, :class => "pp-avatar" %>
                      <% else %>
                          <%= image_tag "picture.gif", class: "pp-avatar" %>
                      <% end %>
                  <% end %>
              <% end %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="text-center">
                <a>
                    <span>
                      <h4 class="menue-username text-success">
                        <% if @user.nil? %>
                           <%= current_user.email %>
                        <% else %>
                            <% if (@user.first_name.present? or @user.middle_name.present? or @user.last_name.present?) %>

                                <% if user_signed_in? %>
                                    <% if @user.first_name.present?%>
                                        <%= @user.first_name.slice(0, 1).capitalize + @user.first_name.slice(1..-1) %>
                                    <% end %>
                                    <% if @user.middle_name.present? %>
                                        <%= @user.middle_name.slice(0, 1).capitalize + @user.middle_name.slice(1..-1) %>
                                    <% end %>
                                    <% if @user.last_name.present?%>
                                        <%= @user.last_name.slice(0, 1).capitalize + @user.last_name.slice(1..-1) %>
                                    <% end %>
                                <% end %>

                            <% else %>
                                <%= current_user.email %>
                            <% end %>
                        <% end %>
                     </h4>
                    </span>
                </a>
              </li>
              <hr class="hrmenu">
              <li>
                <% if @user.nil? %>
                    <a href="<%= new_user_information_path %>">
                        <span>
                          <i class="fa fa-user fa-fw">&nbsp; </i>
                        </span>
                      Profile
                    </a>
                <% else %>
                    <a href="<%= edit_user_information_path(1) %>">
                        <span>
                          <i class="fa fa-user fa-fw">&nbsp; </i>
                        </span>
                      Profile
                    </a>
                <% end %>
              </li>
              <li>
                <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow">
                  <span>
                    <i class="fa fa-sign-out fa-fw">&nbsp;</i>
                  </span>
                  Logout
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $(function () {
    $('li.dropdown a').on('click', function (event) {
      $(this).parent().toggleClass('open');
    });
  });
</script>

app/views/shared/_navigation.html.erb
  <nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="10" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-main" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand logo" href="<%= unauthenticated_root_path %>">
          <strong><span class="text-success">Link</span><span class="text-primary">Store</span></strong></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="navbar-space">
      <div class="collapse navbar-collapse" id="navbar-collapse-main">
        <div class="container">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-plus">&nbsp;</i>Add<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%= new_category_path %>">
                    <span>
                      <i class="fa fa-tree fa-fw">&nbsp;</i>
                    </span>
                    Category
                  </a>
                </li>

                <li>
                  <a href="<%= new_topic_path %>">
                    <span>
                      <i class="fa fa-book fa-fw">&nbsp;</i>
                    </span>Title
                  </a>
                </li>

                <li>
                  <a href="<%= new_link_path %>">
                    <span>
                      <i class="fa fa-link fa-fw">&nbsp;</i>
                    </span>Link
                  </a>
                </li>

              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-binoculars">&nbsp;</i>View<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%= categories_path %>">
                    <span>
                      <i class="fa fa-tree fa-fw">&nbsp;</i>
                    </span>
                    Category
                  </a>
                </li>
                <li>
                  <a href="<%= topics_path %>">
                    <span>
                      <i class="fa fa-book fa-fw">&nbsp;</i>
                    </span>Topics
                  </a>
                </li>
                <li>
                  <a href="<%= links_path %>">
                    <span>
                      <i class="fa fa-link fa-fw">&nbsp;</i>
                    </span>Links
                  </a>
                </li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-star">&nbsp;</i>Favourite<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%= favorite_categories_path %>">
                    <span>
                      <i class="fa fa-tree fa-fw">&nbsp;</i>
                    </span>
                    Category
                  </a>
                </li>
                <li>
                  <a href="<%= favorite_list_topics_path %>">
                    <span>
                      <i class="fa fa-book fa-fw">&nbsp;</i>
                    </span>Topics
                  </a>
                </li>
                <li>
                  <a href="<%= favorite_list_links_path %>">
                    <span>
                      <i class="fa fa-link fa-fw">&nbsp;</i>
                    </span>Links
                  </a>
                </li>
              </ul>
            </li>


          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% @user = UserInformation.find_by_user_id(current_user.id) %>
                <% if @user.nil? %>
                    <%= image_tag "picture.gif", class: "pp-avatar"%>
                <% else %>
                    <% if (@user.first_name.present? or @user.middle_name.present? or @user.last_name.present?) %>
                        <% if @user.photo.present? %>
                            <%= image_tag @user.photo.thumb.url, :class => "pp-avatar" %>
                        <% else %>
                            <%= image_tag "picture.gif", class: "pp-avatar" %>
                        <% end %>
                    <% else %>
                        <% if @user.photo.present? %>
                            <%= image_tag @user.photo.thumb.url, :class => "pp-avatar" %>
                        <% else %>
                          <%= image_tag "picture.gif", class: "pp-avatar" %>
                        <% end %>
                    <% end %>
                <% end %>
              </a>
              <ul class="dropdown-menu">
                <li class="text-center">
                  <a>
                    <span>
                      <h4 class="menue-username text-success">
                        <% if @user.nil? %>
                           <%= current_user.email %>
                        <% else %>
                            <% if (@user.first_name.present? or @user.middle_name.present? or @user.last_name.present?) %>

                                <% if user_signed_in? %>
                                    <% if @user.first_name.present?%>
                                        <%= @user.first_name.slice(0, 1).capitalize + @user.first_name.slice(1..-1) %>
                                    <% end %>
                                    <% if @user.middle_name.present? %>
                                        <%= @user.middle_name.slice(0, 1).capitalize + @user.middle_name.slice(1..-1) %>
                                    <% end %>
                                    <% if @user.last_name.present?%>
                                        <%= @user.last_name.slice(0, 1).capitalize + @user.last_name.slice(1..-1) %>
                                    <% end %>
                                <% end %>

                            <% else %>
                                <%= current_user.email %>
                            <% end %>
                        <% end %>
                     </h4>
                    </span>
                  </a>
                </li>
                <hr class="hrmenu">
                <li>
                  <% if @user.nil? %>
                      <a href="<%= new_user_information_path %>">
                        <span>
                          <i class="fa fa-user fa-fw">&nbsp; </i>
                        </span>
                        Profile
                      </a>
                  <% else %>
                      <a href="<%= edit_user_information_path(1) %>">
                        <span>
                          <i class="fa fa-user fa-fw">&nbsp; </i>
                        </span>
                        Profile
                      </a>
                  <% end %>
                </li>
                <li>
                  <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow">
                  <span>
                    <i class="fa fa-sign-out fa-fw">&nbsp;</i>
                  </span>
                    Logout
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div><!-- /.navbar-collapse -->
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navigationhome.erb
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="10">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>


    <a class="navbar-brand" href="<%= unauthenticated_root_path %>">LinkStore</a>
    <a class="brand" href="<%= unauthenticated_root_path %>">
      <!-- <label class="logo">
           <label class="text-success">Link</label><label class="text-primary">Store</label></label>-->
      <strong><span class="text text-success">Link</span><span class="text text-primary">Store</span></strong>
    </a>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav navbar-right">
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#whattodo">Home</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#features">Features</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#work">Our Work</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#team">Our Team</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#learnmore">Learn More</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="<%= new_user_session_path %>">Login</a></li>
      <li><a data-toggle="collapse" data-target=".navbar-collapse" href="<%= new_user_registration_path %>">Sign Up</a></li>
    </ul>
  </div>
</nav>

app/views/shared/_sidenavigation.html.erb
<ul class="nav nav-pills nav-stacked stick-it sidebar" >
  <li class="nav-item">
    <a class="nav-link active" href="<%= categories_path %>">All Catagories<span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= topics_path %>">All Topics</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">All Links</a>
  </li>
  <li>
    <hr>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Favorites</a>
  </li>

</ul>