config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root  'categories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :categories do
    collection do
      get :manage_categories #for breadcrumbs
      get '/favorite' => :fav_category
    end
    member do
      get '/update' => :update_fav_category
    end
  end

  resources :topics do
    collection do
      get :manage_topics
      get '/favorite/list' => :link_topic
    end
    member do
      get '/category/topics' => :supply_topic
      get '/favorite' => :fav_topic
      get '/update' => :update_fav_topic
    end
  end

  resources :links do
    collection do
      get :manage_links
      get 'favorite/list' => :fav_link_all
    end
    member do
      get '/category/topic/links' => :get_link
      get '/favorite' => :fav_link
      get '/update' => :update_fav_link
    end
  end
  resources :user_informations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  belongs_to :category
  validates :link, presence: true
  before_save :smart_add_url_protocol

  validates :name, :presence => true
  validates_uniqueness_of :name, :scope => [:user_id]
  validates :description, :length => {:maximum => 918}

  def self.supply_links(topic,id,search)
    if search
      where("topic_id = ? and user_id =? and lower(name) like ?", topic, id,  "%#{search.downcase}%").select(:name, :description,:link, :favorite, :id).order("name ASC")
    else
      where("topic_id = ? and user_id =? ", topic, id).select(:name, :description,:link, :favorite, :id).order("name ASC")
    end
  end

  def self.search(topic,id,search)
    if search
      where("topic_id = ? and user_id =? and lower(name) like ? and favorite = ?", topic, id,  "%#{search.downcase}%", true).select(:name, :description,:link, :favorite, :id).order("name ASC")
    else
      where("topic_id = ? and user_id =?  and favorite = ? ", topic, id, true).select(:name, :description,:link, :favorite, :id).order("name ASC")
    end
  end

  def self.fav_search_all(search, id)
    if search
      where("user_id = ? and lower(name) like ? and favorite = ? ", id, "%#{search.downcase}%", true).order("name ASC")
    else
      where("user_id = ? and favorite = ? ",id, true).order("name ASC")
    end
  end

  protected

  def smart_add_url_protocol
    unless self.link[/\Ahttp:\/\//] || self.link[/\Ahttps:\/\//]
      self.link = "https://#{self.link}"
    end
    self.name = self.name.titleize
    self.description = self.description.capitalize
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  add_breadcrumb "Home", :authenticated_root_path
  add_breadcrumb "Link", :links_path
  def new
    @title = "Add"
    add_breadcrumb "New"
    @link = Link.new
    @category_list = Category.where("user_id =? ", current_user.id).select(:name, :id).order("name ASC")
  end

  def create
    @link =Link.new(link_params)
    @link.user_id = current_user.id
    @category_list = Category.where("user_id =? ", current_user.id).select(:name, :id).order("name ASC")
    if @link.save
      flash[:success] = "Link added."
      redirect_to :new_link
    else
      flash[:error] = "Couldn't add link."
      render :new
    end
  end

  def edit
    @title = "Edit"
    add_breadcrumb "Edit"
    @link = Link.find(params[:id])
    @topic = @link.topic_id
    @category_list = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      flash[:success] = "Link added."
      redirect_to "/links/" + @link.topic.id.to_s
    else
      flash[:error] = "Couldn't add link."
      render :edit
    end
  end

  def show
    @title = "Links"
    add_breadcrumb "List"
    @link = Link.supply_links(params[:id],current_user.id, params[:search])
    @perpage = 12
    @links = @link.paginate(:page => params[:page], :per_page => @perpage)
  end

  def index
    @title = "List"
    @category_list = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
  end

  def destroy
    @link = Link.destroy(params[:id])
    if @link.destroyed?
      flash[:success] = "Link Destroyed."
    else
      flash[:alert] = "Unable To Destroy Link."
    end
    @category_list = Category.where("user_id =?", current_user.id).select(:name, :id).order("name ASC")
  end

  def get_link
    @topic = Link.supply_links(params[:id], current_user.id, params[:search])
    render json: @topic
  end

  def fav_link
    @title = "Links"
    add_breadcrumb "List"
    @link = Link.search(params[:id],current_user.id, params[:search])
    @perpage = 12
    @links = @link.paginate(:page => params[:page], :per_page => @perpage)
  end

  def fav_link_all
    @title = "Favourite | List"
    add_breadcrumb "Favourite"
    @link = Link.fav_search_all(params[:search],current_user.id)
    @perpage = 12
    @links = @link.paginate(:page => params[:page], :per_page => @perpage)
  end

  def update_fav_link
    @link = Link.find(params[:id])
    if @link.favorite.present?
      @link.favorite = false
    else
      @link.favorite = true
    end
    @link.save
    render json: @link.favorite
  end

  private

  def link_params
    params.require(:link).permit(:topic_id,:name, :link,:category_id, :favorite,:description)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2  ">

    <% if @link.errors.any? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <ul>
            <% @link.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="well">
      <%= form_for @link do |f| %>
          <div class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-md-3">Category<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <%= f.collection_select :category_id, @category_list, :id, :name, {prompt: "Select Category"}, :class => "form-control select category-select" %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Topic<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <%= f.select(:topic_id, options_for_select([["Select Topic",""]]),{},{:class=>"form-control select topic-select"})%>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Name <span class="text-danger">*</span></label>
              <div class="col-md-9">
                <% if @link.errors[:name].any? %>
                    <%= f.text_field :name, :class=>"form-control", :placeholder => "Youtube", :style => "border-color: red; background-color: rgb(255, 230, 230);" %>
                <% else %>
                    <%= f.text_field :name, :class=>"form-control", :placeholder => "Youtube" %>
                <% end %>

              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Link <span class="text-danger">*</span></label>
              <div class="col-md-9">
                <% if @link.errors[:link].any? %>
                  <%= f.text_field :link, :class=>"form-control", :placeholder => "https://www.youtube.com", :style => "border-color: red; background-color: rgb(255, 230, 230);" %>
                <% else %>
                  <%= f.text_field :link, :class=>"form-control", :placeholder => "https://www.youtube.com" %>
                <% end %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Description </label>
              <div class="col-md-9">
                <%= f.text_area :description,:rows => 4, :style => "resize: none;", :class=>"form-control", :placeholder => "Few words describing this link." %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Favorite </label>
              <div class="col-md-9">
                <div class="check-box">
                  <%= f.check_box :favorite %>
                </div>
              </div>
            </div>


            <div class="form-group">
              <div class="col-md-offset-3 col-md-4">
                <%= f.submit "Submit", :class => "btn btn-primary"%>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
 $('body').on('change','.category-select', function(){
   var category = $('.category-select'),
       topic = $('.topic-select');
   if (category.val() == '') {
     topic.empty().append(new Option("Select Topic", " "))
   }else{
     $.ajax({
       url: '/topics/' + category.val() + '/category/topics',
       error: function () {
         console.log("error");
       },
       success: function (data) {
         if (!$.trim(data)){
           topic.empty().append(new Option("Select Topic", " "))
         }else{
           topic.empty().append(new Option("Select Topic", " "))
           for (var i = 0; i < data.length; i++) {
             var id = data[i].id;
             var title = data[i].name;
             topic.append(new Option(title, id));
           }
         }
       },
       type: 'GET'
     });
   }
 });
 $(document).ready(function(){
   var category = $('.category-select'),
       topic = $('.topic-select');
   if (category.val() == '') {
     topic.empty().append(new Option("Select Topic", " "))
   }else{
     $.ajax({
       url: '/topics/' + category.val() + '/category/topics',
       error: function () {
         console.log("error");
       },
       success: function (data) {
         var options = "";
         if (!$.trim(data)){
           topic.empty().append(new Option("Select Topic", " "));
         }else{
           topic.empty().append(new Option("Select Topic", " "));
           for (var i = 0; i < data.length; i++) {
             <% if @topic.present? %>
               if (data[i].id == <%= @topic %>){
                 topic.empty().append(new Option(data[i].name, data[i].id));
               }else{
                 options += '<option value="' +data[i].id + '">' +data[i].name + '<>';
               }
             <% else %>
              topic.empty().append(new Option("Select Topic", " "));
             <% end %>
           }
           topic.append(options);
         }
       },
       type: 'GET'
     });
   }
 });
</script>

app/views/links/fav_link.html.erb
<div class="catagory">
  <div class="row">

    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag link_path, method: 'get' do %>
            <div class="col-xs-12 col-sm-8 col-md-6 form-group">
              <%= text_field_tag :search, params[:search], :class => "form-control" %>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_topic_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>

    <div class="col-xs-12 col-md-12">
      <hr>
    </div>

    <div class="col-md-12 ">
      <% if !@links.present? %>
          <div class="text-center text-primary">
            <h3>Links not created.</h3>
            <a href="<%= new_link_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a>
          </div>
      <% else %>
          <% @links.each do |f| %>
              <div class="col-md-6 ">
                <div class="panel panel-primary">
                  <div class="panel-body">

                    <div class="fa-icon">
                      <div class="pull-right">
                        <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="<%= link_path(f) %>">
                            <span>
                              <i class="fa fa-trash fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <a href="<%= edit_link_path(f) %>">
                            <span>
                              <i class="fa fa-edit fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <% if f.favorite %>
                            <i class="fa fa-star category-fav fa-hide" style="color: #f4bd2b">&nbsp;</i>
                        <% else %>
                            <i class="fa fa-star category-fav fa-hide" name="<%= f.id %>">&nbsp;</i>
                        <% end %>
                        <a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= f.description %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                      </div>
                    </div>

                    <div class="databody">
                      <a itemprop="url" href="<%= f.link%>">
                        <h2 class="post-title"><%= f.name %></h2>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @links, renderer: BootstrapPagination::Rails %>

app/views/links/fav_link_all.html.erb
<div class="catagory">
  <div class="row">

    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag favorite_list_links_path, method: 'get' do %>
            <div class="col-xs-12 col-sm-8 col-md-6 form-group">
              <%= text_field_tag :search, params[:search], :class => "form-control" %>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_topic_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>

    <div class="col-xs-12 col-md-12">
      <hr>
    </div>

    <div class="col-md-12 ">
      <% if !@links.present? %>
          <div class="text-center text-primary">
            <h3>There are no any favourite link for this topic.</h3>
          </div>
      <% else %>
          <% @links.each do |f| %>
              <div class="col-md-6 ">
                <div class="panel panel-primary">
                  <div class="panel-body">
                    <div class="fa-icon">
                      <div class="pull-right">
                        <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="<%= link_path(f) %>">
                            <span>
                              <i class="fa fa-trash fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <a href="<%= edit_link_path(f) %>">
                            <span>
                              <i class="fa fa-edit fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <% if f.favorite %>
                            <i class="fa fa-star link-fav fa-hide" name="<%= f.id %>" style="color: #f4bd2b">&nbsp;</i>
                        <% else %>
                            <i class="fa fa-star link-fav fa-hide" name="<%= f.id %>" >&nbsp;</i>
                        <% end %>
                        <a tabindex="0" role="button" data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= f.description %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                      </div>
                    </div>

                    <div class="databody">
                      <a itemprop="url" href="<%= f.link %>">
                        <h2 class="post-title"><%= f.name %></h2>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @links, renderer: BootstrapPagination::Rails %>

<script type="text/javascript" charset="utf-8">
  $('body').on('click','.link-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.link-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/links/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
  });

  $(document).ready(function () {
    $('[data-toggle="popover"]').popover();
  });
</script>

app/views/links/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <label class="col-md-4 control-label text-right">Category</label>
      <div class="col-md-8 ">
        <%= select_tag 'catagoryid', options_for_select(@category_list.collect { |u| [u.name, u.id] }), :prompt => "Select Unit", :class => "form-control select category-select" %>
      </div>
    </div>

    <div class="col-md-4">
      <label class="col-md-4 control-label text-right">Topic</label>
      <div class="col-md-8 ">
        <select class="form-control select select-topic">
          <option value="">Select Topic</option>
        </select>
      </div>
    </div>

    <div class="col-md-4">
      <div class="col-xs-12 col-sm-8 col-md-6 form-group">
        <input type="text" class="form-control input-search">
      </div>
      <div class="col-xs-12 col-sm-4 col-md-6">
        <p class="btn btn-success btn-search">Search</p>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <br>
    <hr>
    <br>
  </div>
  <div class="col-md-12 link catagory">
    <div class="text-center text-primary link-remove category-remove">
      <h3>Links not created.</h3>
      <a href="<%= new_topic_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $('body').on('change', '.select-topic', function () {
    var selectbox = $('.select-topic');
    if (selectbox.val() != '') {
      $.ajax({
        url: '/links/' + selectbox.val() + '/category/topic/links',
        error: function () {
          $('#info').html('<p>An error has occurred</p>');
        },
        success: function (data) {
          if (!$.trim(data)) {
            $('div.link-remove').remove();
            var add_div = '<div class="text-center text-primary link-remove catagory-remove"><h3>Links not created.</h3> <a href="/links/new" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a> </div>';
            $('div.link').append(add_div);
          } else {
            $('div.link-remove').remove();
            for (i = 0; i < data.length; i++) {
              var adddata = "";
              adddata = '<div class="col-md-6 link-remove category-remove"><div class="panel panel-primary" >';
              adddata += ' <div class="panel-body"><div class="fa-icon"><div class="pull-right"><a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="/links/' + data[i].id ;
              adddata += '"><span><i class="fa fa-trash ">&nbsp;</i></span></a><a href="links/' + data[i].id +'/edit';
              adddata += '"><span><i class="fa fa-edit ">&nbsp;</i></span></a>';
              if (data[i].favorite == true){
                adddata += '<i class="fa fa-star link-fav fa-hide" style="color: #f4bd2b" name="' + data[i].id + '">&nbsp;</i>';
              }else{
                adddata += ' <i class="fa fa-star link-fav fa-hide" name="' + data[i].id + '" >&nbsp;</i>';
              }
              adddata += '<a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="' + data[i].description + '"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>';
              adddata += '</div></div><div class="databody"> <a itemprop="url" href="'+ data[i].link + '" target="_blank">';
              adddata += '<h2 class="post-title">' + data[i].name + '</h2></a></div></div></div>';
              $('div.link').append(adddata);
            }

          }
        },
        type: 'GET'
      });
    }else{
      $('div.link-remove').remove();
      var add_div = '<div class="text-center text-primary link-remove catagory-remove"><h3>Links not created.</h3> <a href="/links/new" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a> </div>';
      $('div.link').append(add_div);
    }
  });

  $('body').on('click', '.btn-search', function () {
    var selectbox = $('.select-topic');
    if (selectbox.val() != '') {
      $.ajax({
        url: '/links/' + selectbox.val() + '/category/topic/links?utf8=✓&search=' + $('.input-search').val(),
        error: function () {
          $('#info').html('<p>An error has occurred</p>');
        },
        success: function (data) {
          if (!$.trim(data)) {
            $('div.link-remove').remove();
            var add_div = '<div class="text-center text-primary link-remove category-remove"><h3>Topics not created for this catagory.</h3> <a href="/topics/new" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a> </div>'
            $('div.link').append(add_div);
          } else {
            $('div.link-remove').remove();
            for (i = 0; i < data.length; i++) {
              var adddata = "";
              adddata = '<div class="col-md-6 link-remove category-remove"><div class="panel panel-primary" title="' + data[i].description + '">';
              adddata += ' <div class="panel-body"><div class="fa-icon"><div class="pull-right"><a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="/links/' + data[i].id ;
              adddata += '"><span><i class="fa fa-trash ">&nbsp;</i></span></a><a href="links/' + data[i].id +'/edit';
              adddata += '"><span><i class="fa fa-edit ">&nbsp;</i></span></a>';
              if (data[i].favorite == true){
                adddata += '<i class="fa fa-star link-fav fa-hide" name="' + data[i].id + '"style="color: #f4bd2b" >&nbsp;</i>';
              }else{
                adddata += ' <i class="fa fa-star link-fav fa-hide" name="' + data[i].id + '">&nbsp;</i>';
              }
              adddata += '<a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="' + data[i].description + '"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>';
              adddata += '</div></div><div class="databody"> <a itemprop="url" href="'+ data[i].link + '" target="_blank">';
              adddata += '<h2 class="post-title">' + data[i].name + '</h2></a></div></div></div>';
              $('div.link').append(adddata);
            }

          }
        },
        type: 'GET'
      });
    }
    $('[data-toggle="popover"]').popover();
  });

  $('body').on('change', '.category-select', function () {
    var category = $('.category-select'),
        topic = $('.select-topic');
    if (category.val() == '') {
      topic.empty().append(new Option("Select Topic", " "));
    }else{
      $.ajax({
        url: '/topics/' + category.val() + '/category/topics',
        error: function () {
          console.log("error");
        },
        success: function (data) {
          if (!$.trim(data)){
            topic.empty().append(new Option("Select Topic", " "));
          }else{
            topic.empty().append(new Option("Select Topic", " "));
            for (var i = 0; i < data.length; i++) {
              var id = data[i].id;
              var title = data[i].name;
              topic.append(new Option(title, id));
            }
          }
        },
        type: 'GET'
      });
    }
  });

  $('body').on('click','.link-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.link-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/links/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
    $('[data-toggle="popover"]').popover();
  });

  $(document).ready(function () {
    $('[data-toggle="popover"]').popover();
  });
</script>

app/views/links/show.html.erb
<div class="catagory">
  <div class="row">

    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag link_path, method: 'get' do %>
            <div class="col-xs-12 col-sm-8 col-md-6 form-group">
              <%= text_field_tag :search, params[:search], :class => "form-control" %>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_topic_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>

    <div class="col-xs-12 col-md-12">
      <hr>
    </div>

    <div class="col-xs-12 col-md-12 ">
      <% if !@links.present? %>
          <div class="text-center text-primary">
            <h3>Links not created.</h3>
            <a href="<%= new_link_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;&nbsp;</i>Create</a>
          </div>
      <% else %>
          <% @links.each do |f| %>
              <div class="col-md-6 ">
                <div class="panel panel-primary">
                  <div class="panel-body">
                    <div class="fa-icon">
                      <div class="pull-right">
                        <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="<%= link_path(f) %>">
                            <span>
                              <i class="fa fa-trash fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <a href="<%= edit_link_path(f) %>" data-toggle="toggle" title="Edit Record">
                            <span>
                              <i class="fa fa-edit fa-hide">&nbsp;</i>
                            </span>
                        </a>
                        <% if f.favorite %>
                            <i class="fa fa-star link-fav fa-hide"  data-toggle="toggle" title="Favourite" name="<%= f.id %>" style="color: #f4bd2b">&nbsp;</i>
                        <% else %>
                            <i class="fa fa-star link-fav fa-hide"  data-toggle="toggle" title="Favourite" name="<%= f.id %>" >&nbsp;</i>
                        <% end %>
                        <a tabindex="0" role="button" data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= f.description %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                      </div>
                    </div>

                    <div class="databody">
                      <a itemprop="url" href="<%= f.link %>" target = "_blank">
                        <h2 class="post-title"><%= f.name %></h2>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @links, renderer: BootstrapPagination::Rails %>

<script type="text/javascript" charset="utf-8">
  $('body').on('click','.link-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.link-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/links/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
  });

  $(document).ready(function () {
    $('[data-toggle="popover"]').popover();
    $('[data-toggle="toggle"]').tooltip();
  });
</script>