config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root  'categories#index', as: :authenticated_root
    end

    unauthenticated :user do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :categories do
    collection do
      get :manage_categories #for breadcrumbs
      get '/favorite' => :fav_category
    end
    member do
      get '/update' => :update_fav_category
    end
  end

  resources :topics do
    collection do
      get :manage_topics
      get '/favorite/list' => :link_topic
    end
    member do
      get '/category/topics' => :supply_topic
      get '/favorite' => :fav_topic
      get '/update' => :update_fav_topic
    end
  end

  resources :links do
    collection do
      get :manage_links
      get 'favorite/list' => :fav_link_all
    end
    member do
      get '/category/topic/links' => :get_link
      get '/favorite' => :fav_link
      get '/update' => :update_fav_link
    end
  end
  resources :user_informations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :topics, :dependent => :destroy
  has_many :links, :dependent => :destroy
  belongs_to :user

  validates :name, presence: true
  validates_uniqueness_of :name, :scope => [:user_id]
  validates :description, :length => {:maximum => 918}

  def self.search(search, id)
    if search
      where("user_id = ? and lower(name) like ? ",id, "%#{search.downcase}%").order("name ASC")
    else
      where("user_id = ?", id).order("name ASC")
    end
  end

  def self.fav_search(search, id)
    if search
      where("user_id = ? and favorite = ? and lower(name) like ? ",id, true, "%#{search.downcase}%").order("name ASC")
    else
      where("user_id = ? and favorite = ?", id, true).order("name ASC")
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  add_breadcrumb "Home", :authenticated_root_path
  def new
    @title = "Add"
    add_breadcrumb "New"
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.name = @category.name.titleize
    @category.user_id = current_user.id
    if @category.save
      flash[:success] = "Category Created."
      redirect_to :categories
    else
      flash[:error] = "Unable to create Category."
      render "new"
    end
  end

  def edit
    @title = "Edit"
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category Updated."
      redirect_to :categories
    else
      flash[:error] = "unable to update category."
      render "edit"
    end
  end

  def destroy
    @category = Category.destroy(params[:id])
    if @category.destroyed?
      flash[:success] = "Category Deleted."
    else
      flash[:error] = "Unable to delete category."
    end
    redirect_to :categories
  end

  def index
    @check_title = "Catatogy"
    @title = "List"
    @perpage = 12
    @category = Category.search(params[:search], current_user.id)
    @categories = @category.paginate(:page => params[:page], :per_page => @perpage)
  end

  def fav_category
    @check_title = "Catatogy"
    @title = "List"
    @perpage = 12
    @category = Category.fav_search(params[:search], current_user.id)
    @categories = @category.paginate(:page => params[:page], :per_page => @perpage)
  end

  def update_fav_category
    @category = Category.find(params[:id])
    if @category.favorite.present?
      @category.favorite = false
    else
      @category.favorite = true
    end
    @category.save
    render json: @category.favorite
  end

  private

  def category_params
    params.require(:category).permit(:name, :description,:favorite)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2 ">

      <% if @category.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <ul>
              <% @category.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="well">
        <%= form_for @category do |f| %>
          <div class="form-horizontal">
            <div class="form-group">
              <label class="control-label col-md-3">Name <span class="text-danger">*</span></label>
              <div class="col-md-9">
                <%= f.text_field :name, :class=>"form-control", :placeholder => "Youtube" %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Description </label>
              <div class="col-md-9">
                <%= f.text_area :description,:rows => 4, :style => "resize: none;", :class=>"form-control", :placeholder => "Links related to videos." %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3">Favorite </label>
              <div class="col-md-9">
                <div class="check-box">
                  <%= f.check_box :favorite %>
                </div>
              </div>
            </div>


            <div class="form-group">
              <div class="col-md-offset-3 col-md-4">
                <%= f.submit "Submit", :class => "btn btn-primary"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/fav_category.html.erb
<div class="catagory">
  <div class="row">
    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag favorite_categories_path, method: 'get' do %>
            <div class="col-xs-12 col-sm-8 col-md-6 form-group">
              <%= text_field_tag :search, params[:search], :class => "form-control" %>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_category_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>
    <div class="col-xs-12 col-md-12">
      <hr>
    </div>
    <div class="col-xs-12 col-md-12">
      <% if !@categories.present? %>
          <div class="text-center text-primary">
            <h3>Category not created for this user.</h3>
            <a href="<%= new_category_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;</i>Create New</a>
          </div>
      <% else %>
          <% @categories.each do |f| %>

            <div class="col-md-6 ">
              <div class="panel panel-primary">
                <div class="panel-body">

                  <div class="fa-icon">
                    <div class="pull-right">
                      <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete Record" data-toggle="toggle" data-method="delete" href="<%= category_path(f) %>">
                          <span>
                            <i class="fa fa-trash fa-hide">&nbsp;</i>
                          </span>
                      </a>
                      <a href="<%= edit_category_path(f) %>">
                          <span>
                            <i class="fa fa-edit fa-hide">&nbsp;</i>
                          </span>
                      </a>
                      <% if f.favorite %>
                          <i class="fa fa-star category-fav fa-hide" name="<%= f.id %>" style="color: #f4bd2b">&nbsp;</i>
                      <% else %>
                          <i class="fa fa-star category-fav fa-hide" name="<%= f.id %>" >&nbsp;</i>
                      <% end %>
                      <a tabindex="0" role="button" class="popovertitle " data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= f.description %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                    </div>
                  </div>

                  <div class="databody">
                    <a itemprop="url" href="<%= favorite_topic_path(f) %>">
                      <h2 class="post-title"><%= f.name %></h2>
                    </a>
                  </div>
                </div>
              </div>
            </div>

          <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 pull-right">
      <%= will_paginate @catagories, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $('body').on('click','.category-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.category-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/categories/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
  });

  $(document).ready(function () {
    $('[data-toggle="popover"]').popover();
  });
</script>

app/views/categories/index.html.erb
<div class="catagory">
  <div class="row">
    <div class="col-xs-12 col-md-12 ">
      <div class="col-xs-12 col-sm-8 col-md-6">
        <%= form_tag categories_path, method: 'get' do %>
          <div class="col-xs-12 col-sm-8 col-md-6 form-group">
            <%= text_field_tag :search, params[:search], :class => "form-control" %>
          </div>
            <div class="col-xs-12 col-sm-4 col-md-6">
              <%= submit_tag "Search", :name => nil, :class => "btn btn-success" %>
            </div>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-6">
        <a href="<%= new_category_path %>" class="btn btn-primary pull-right"><i class="fa fa-plus">&nbsp;</i>Add</a>
      </div>
    </div>
    <div class="col-xs-12 col-md-12">
      <hr>
    </div>

    <div class="col-xs-12 col-md-12">
      <% if !@categories.present? %>
          <div class="text-center text-primary">
            <h3>Catagory not created for this user.</h3>
            <a href="<%= new_category_path %>" class="btn btn-success"> <i class="fa fa-plus">&nbsp;</i>Create New</a>
          </div>
      <% else %>
          <% @categories.each do |f| %>
              <% if (f.description.present?)
                   @value = f.description
                 else
                   @value = "No Description."
                 end%>
              <div class="col-md-6 ">
                <div class="panel panel-primary">
                  <div class="panel-body">

                      <div class="fa-icon">
                        <div class="pull-right">
                          <a data-confirm="Are you sure to delete" rel="nofollow" title="Delete" data-toggle="toggle" data-method="delete" href="<%= category_path(f)%>">
                            <span>
                              <i class="fa fa-trash fa-hide">&nbsp;</i>
                            </span>
                          </a>
                          <a href="<%= edit_category_path(f) %>" title="Edit" data-toggle="toggle">
                            <span>
                              <i class="fa fa-edit fa-hide">&nbsp;</i>
                            </span>
                          </a>
                          <% if f.favorite %>
                              <i class="fa fa-star category-fav fa-hide" title="Favourite" data-toggle="toggle" name="<%= f.id %>" style="color: #f4bd2b">&nbsp;</i>
                          <% else %>
                              <i class="fa fa-star category-fav fa-hide" title="Favorite" data-toggle="toggle" name="<%= f.id %>" >&nbsp;</i>
                          <% end %>
                          <a tabindex="0" role="button" class="popovertitle" data-container="body" data-placement="bottom" title="Description" data-toggle="popover" data-trigger="focus" data-content="<%= f.description %>"><i class="fa fa-eye text-info text-right" style="color: #648fa5;"></i></a>
                        </div>
                      </div>

                      <div class="databody">
                        <a itemprop="url" href="<%= topic_path(f) %>">
                          <h2 class="post-title"><%= f.name %></h2>
                        </a>
                      </div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 pull-right">
      <%= will_paginate @catagories, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $('body').on('click','.category-fav',function(e){
    var row = $(this).closest('div');
    var fav = $('.category-fav',row);
    var name_value = fav.attr("name");
    $.ajax({
      url: '/categories/' + name_value + '/update',
      error: function () {
        $('#info').html('<p>An error has occurred</p>');
      },
      success: function (data) {
        if (data != ''){
          fav.css('color','#f4bd2b');
        }else{
          fav.css('color','#c2c2c2');
        }
      },
      type: 'GET'
    });
  });

  $(document).ready(function () {
    $('[data-toggle="popover"]').popover();
    $('[data-toggle="toggle"]').tooltip();
  });
</script>